### ISSUE TITLE
As a user I want to upload opportunity data using CSV file. 

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/hooghlycrm#459]
Check the lead example.
Acceptance
1> Opportunity data is read from CSV file
2> Opportunity data is saved in DB
3> Import details form is displayed.

** No notification required or log / report generation required now. Those enhancements can be handled later by another issue.

**Comment by Rajiv-mar121** [comment]
Ok Dhrubo will start this story .

Regards,
Rajiv

On Fri, Mar 9, 2018 at 11:55 PM, Dhrubojyoti Kayal <notifications@github.com
